#!/usr/bin/env sh
# commit-defender pre-commit hook
# Auto-generated by: commit-defender install
# Do not edit by hand — re-run install to regenerate.
#
# Runner modes:
#   docker (default): COMMIT_DEFENDER_IMAGE=commit-defender:v1.x commit-defender install
#   local:            COMMIT_DEFENDER_MODE=local COMMIT_DEFENDER_PYTHON=python3 commit-defender install
# To bypass (not recommended): git commit --no-verify

set -e

# Resolve repo root (works in worktrees too)
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Collect staged files: Added, Copied, Modified, Renamed (exclude Deleted)
STAGED="$(git diff --cached --name-only --diff-filter=ACMR)"

# Nothing staged = nothing to check
if [ -z "$STAGED" ]; then
    exit 0
fi

# Runner mode: 'docker' (default) or 'local'
MODE="${COMMIT_DEFENDER_MODE:-{{MODE}}}"

# ── Local mode: run Python directly (no Docker required) ──────────────────────
if [ "${MODE}" = "local" ]; then
    PYTHON="${COMMIT_DEFENDER_PYTHON:-{{PYTHON}}}"
    if ! command -v "${PYTHON}" >/dev/null 2>&1; then
        echo "commit-defender: python not found at '${PYTHON}' — skipping." >&2
        exit 0
    fi
    export CD_REPO_PATH="${REPO_ROOT}"
    export CD_STAGED_FILES="${STAGED}"
    "${PYTHON}" -m commit_defender.entrypoint 1>&2
    exit $?
fi

# ── Docker mode ───────────────────────────────────────────────────────────────

# Credentials are loaded inside the container from (highest priority first):
#   1. Environment variables (os.environ)
#   2. .commit-defender.env in the repo root
#   3. ~/.commit-defender.env (home fallback)
HOME_ENV="${HOME}/.commit-defender.env"

# Build optional home-dir mount flag
HOME_ENV_MOUNT=""
if [ -f "$HOME_ENV" ]; then
    HOME_ENV_MOUNT="-v ${HOME_ENV}:/run/secrets/home.env:ro"
fi

IMAGE="${COMMIT_DEFENDER_IMAGE:-{{IMAGE}}}"

# Check docker is available
if ! command -v docker >/dev/null 2>&1; then
    echo "commit-defender: docker not found — skipping pre-commit checks." >&2
    echo "  To run without Docker: reinstall with COMMIT_DEFENDER_MODE=local" >&2
    exit 0
fi

# Check the image exists locally
if ! docker image inspect "${IMAGE}" >/dev/null 2>&1; then
    echo "commit-defender: image '${IMAGE}' not found locally." >&2
    echo "Build it with:  docker build -t ${IMAGE} <path-to-commit-defender-repo>" >&2
    echo "Skipping pre-commit checks." >&2
    exit 0
fi

# Run the validator container:
#   Credentials are mounted read-only — never appear in docker run args or docker inspect.
#   Only non-secret operational vars are passed via -e.
docker run --rm \
    -v "${REPO_ROOT}:/repo:ro" \
    ${HOME_ENV_MOUNT} \
    -e CD_STAGED_FILES="${STAGED}" \
    -e CD_REPO_PATH="/repo" \
    "${IMAGE}" 1>&2

exit $?
