#!/usr/bin/env sh
# commit-defender pre-commit hook
# Auto-generated by: commit-defender install
# Do not edit by hand — re-run install to regenerate.
#
# To update the image tag: COMMIT_DEFENDER_IMAGE=commit-defender:v1.x commit-defender install
# To bypass (not recommended): git commit --no-verify

set -e

# Resolve repo root (works in worktrees too)
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Allow image override via env var
IMAGE="${COMMIT_DEFENDER_IMAGE:-{{IMAGE}}}"

# Collect staged files: Added, Copied, Modified, Renamed (exclude Deleted)
STAGED="$(git diff --cached --name-only --diff-filter=ACMR)"

# Nothing staged = nothing to check
if [ -z "$STAGED" ]; then
  exit 0
fi

# Check docker is available
if ! command -v docker >/dev/null 2>&1; then
  echo "commit-defender: docker not found — skipping pre-commit checks." >&2
  echo "Install Docker to enable commit-defender: https://docs.docker.com/get-docker/" >&2
  exit 0
fi

# Check the image exists locally; try to pull if not
if ! docker image inspect "${IMAGE}" >/dev/null 2>&1; then
  echo "commit-defender: image '${IMAGE}' not found locally." >&2
  echo "Build it with:  docker build -t ${IMAGE} <path-to-commit-defender-repo>" >&2
  echo "Skipping pre-commit checks." >&2
  exit 0
fi

# Run the validator container:
#   -v repo:ro  — mount the repo read-only
#   1>&2        — redirect stdout → stderr (git captures stdout for commit messages)
docker run --rm \
  -v "${REPO_ROOT}:/repo:ro" \
  -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}" \
  -e CD_STAGED_FILES="${STAGED}" \
  -e CD_REPO_PATH="/repo" \
  "${IMAGE}" 1>&2

# Forward the container's exit code to git
exit $?
